# Generated by Django 4.2.6 on 2023-10-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_dadosclientesmodel_id_alter_itempedidomodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
